export const TEXTS = {
  APP_NAME: "MoodSound",
  APP_DESCRIPTION: "Tu biblioteca musical organizada por emociones",

  NAV: {
    HOME: "Inicio",
    CANCIONES: "Canciones",
    ABOUT: "Acerca de",
  },

  HOME: {
    WELCOME: "Bienvenido a MoodSound",
    SUBTITLE: "Organiza tu música según cómo te hace sentir",
    FEATURE_1_TITLE: "Gestiona tu música",
    FEATURE_1_DESC: "Añade, edita y elimina canciones de tu colección personal.",
    FEATURE_2_TITLE: "Filtra por mood",
    FEATURE_2_DESC: "Encuentra canciones según tu estado de ánimo actual.",
    FEATURE_3_TITLE: "Busca rápido",
    FEATURE_3_DESC: "Filtra por título, artista o mood en tiempo real.",
    CTA: "Ir a mis canciones",
  },

  ABOUT: {
    TITLE: "Acerca de MoodSound",
    INTRO: "MoodSound nació de una idea simple: la música que escuchamos está conectada con cómo nos sentimos.",
    HOW_TITLE: "¿Cómo funciona?",
    HOW_STEPS: [
      "Inicia sesión con tus credenciales",
      "Añade canciones con su título, artista y estado de ánimo",
      "Usa los filtros para encontrar la canción perfecta para cada momento",
      "Edita o elimina canciones cuando quieras",
    ],
    TECH_TITLE: "Tecnologías",
    TECH_FRONTEND: "React 19 + Vite 7",
    TECH_BACKEND: "Express 5 + Node.js",
    TECH_DB: "MongoDB Atlas + Mongoose",
  },

  LOGIN: {
    SUBTITLE: "Introduce tu usuario y tu contraseña",
    EMAIL_PLACEHOLDER: "email",
    PASS_PLACEHOLDER: "contraseña",
    SUBMIT: "Entrar",
    SUBMIT_LOADING: "Entrando...",
    DEMO_LABEL: "Usuario demo:",
    ERROR_EMPTY: "Rellena usuario y contraseña",
    ERROR_INVALID: "Credenciales inválidas",
  },

  CANCIONES: {
    ADD_TITLE: "Añadir canción",
    ADD_HELP: "Rellena título, artista y el estado de ánimo",
    ADD_SUBMIT: "Añadir",
    ADD_SUBMIT_LOADING: "Añadiendo...",
    SEARCH_TITLE: "Buscar canciones",
    FILTER_SUBMIT: "Filtrar",
    PLACEHOLDER_TITULO: "título",
    PLACEHOLDER_ARTISTA: "artista",
    PLACEHOLDER_MOOD: "mood",
    FILTER_TITULO: "filtrar por título",
    FILTER_ARTISTA: "filtrar por artista",
    FILTER_MOOD: "filtrar por mood",
    EMPTY: "No hay canciones. Añade la primera o cambia los filtros.",
    LOADING: "Cargando canciones…",
    MSG_CREATED: "Canción añadida correctamente 🎵",
    MSG_DELETED: "Canción eliminada 🗑️",
    MSG_UPDATED: "Cambios guardados ✅",
    ERR_LOAD: "No se pudieron cargar las canciones",
    ERR_CREATE: "No se pudo crear la canción",
    ERR_DELETE: "No se pudo eliminar la canción",
    ERR_UPDATE: "No se pudo actualizar la canción",
    BTN_EDIT: "Editar",
    BTN_DELETE: "Eliminar",
    BTN_SAVE: "Guardar",
    BTN_CANCEL: "Cancelar",
    BTN_LOGOUT: "Salir",
    NO_MOOD: "—",
  },
}
